id: org.firewalld.firewall-config
runtime: org.gnome.Platform
runtime-version: "50"
sdk: org.gnome.Sdk
command: firewall-config
finish-args:
  - --socket=wayland
  - --device=dri
  - --socket=fallback-x11
  - --share=ipc
  - --system-talk-name=org.freedesktop.NetworkManager
  - --system-talk-name=org.fedoraproject.FirewallD1
cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - "*.la"
  - "*.a"
rename-icon: firewall-config
rename-desktop-file: firewall-config.desktop
modules:
  - name: firewalld
    sources:
      - type: git
        url: https://github.com/firewalld/firewalld.git
        tag: v2.4.3
        commit: 865b0da0a73927b152ab6d2f7c1da9a03f5d4a51
        x-checker-data:
          type: anitya
          project-id: 9989
          stable-only: true
          tag-template: v$version
      - type: patch
        path: ./0001-remove-subdirs.patch
      - type: patch
        path: ./0002-datadir.patch
      - type: patch
        path: ./0004-icon.patch
      - type: file
        path: ./org.firewalld.firewall-config.releases.xml
      - type: shell # monster shell script (ik its ugly)
        commands:
        - sed -i -e '/content_rating/a \ \ <releases type="external"/>' config/org.firewalld.firewall-config.metainfo.xml.in
        - install -Dm644 org.firewalld.firewall-config.releases.xml -t /app/share/metainfo/releases
    modules:
      - shared-modules/intltool/intltool-0.51.json
      - nm-dep.yaml

  - name: dbus-python
    buildsystem: autotools
    cleanup:
      - /include
    sources:
      - type: archive
        url: https://dbus.freedesktop.org/releases/dbus-python/dbus-python-1.4.0.tar.xz
        sha256: c36b28f10ffcc8f1f798aca973bcc132f91f33eb9b6b8904381b4077766043d5
        x-checker-data:
          type: anitya
          project-id: 402
          url-template: https://dbus.freedesktop.org/releases/dbus-python/dbus-python-$version.tar.xz
